# Generated by Django 3.2.11 on 2022-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('username', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('password', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('password2', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
