# Generated by Django 3.2.11 on 2022-01-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(default=models.CharField(default='DEFAULT VALUE', max_length=50), max_length=50),
        ),
    ]
