# Generated by Django 3.2.11 on 2022-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220223_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='DEFAULT VALUE', max_length=500),
        ),
    ]
