# Generated by Django 3.2.11 on 2022-01-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
