# Generated by Django 3.2.11 on 2022-01-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
