# Generated by Django 3.2.11 on 2022-02-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_rename_accounts_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastefile',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
